version: '3'

networks:
  abilityLink_backend:

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: wum2004/node-service:latest
    volumes:
      - .:/app
      - ./node_modules/:/app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm audit fix && npm run build"

  vite:
    build:
      context: .
      dockerfile: Dockerfile-vite
    image: wum2004/vite-service:latest
    depends_on:
      node:
        condition: service_completed_successfully
    working_dir: /app
    ports:
      - 5173:5173
    networks:
      - abilityLink_backend
    volumes:
      - .:/app
    entrypoint: npm run dev -- --host 0.0.0.0
