name: Docker Image CI

on:
  release:
    types: [published, edited]

env:
  PACK_BUILDER: 'heroku/buildpacks:20'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Login to Docker Hub
      run: docker login -u wum2004 -p dckr_pat_zmtO6E5ohRoCnnbdxjZ25CtaY9k

    - name: Build and push Docker image
      run: |
        docker build -t wum2004/frontend:latest .
        docker push wum2004/frontend:latest

  refresh:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Refresh Server
      shell: cmd
      run: az container restart --name frontend --resource-group AbilityLink
