name: Docker Image CI

on:
  push:
    branches: [ "CIN" ]
  pull_request:
    branches: [ "CIN" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u wum2004 -p dckr_pat_zmtO6E5ohRoCnnbdxjZ25CtaY9k

    - name: Build and push Docker image
      run: |
        docker build -t wum2004/frontend:latest .
        docker push wum2004/frontend:latest