name: Docker Image CI Update

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Choose a tag to trigger the workflow'
        required: true

env:
  PACK_BUILDER: 'heroku/buildpacks:20'

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch tags from GitHub API
      id: fetch-tags
      run: |
        tags=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/tags" | \
                jq -r '.[].name')
        echo "::set-output name=tags::$tags"

    - name: Display available tags
      run: echo "Available tags: ${{ steps.fetch-tags.outputs.tags }}"

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Login to Docker Hub
      run: docker login -u wum2004 -p dckr_pat_zmtO6E5ohRoCnnbdxjZ25CtaY9k

    - name: Build and push Docker image
      run: |
        docker build -t wum2004/frontend:latest .
        docker push wum2004/frontend:latest

  refresh:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Refresh Server
      shell: cmd
      run: az container restart --name frontend --resource-group AbilityLink
